name: Build
on: [push]
jobs:
  tests:
    runs-on: macos-latest
    name: Unit Tests
    steps:
    - name: Checkout Project
      uses: actions/checkout@v3
    - name: Install Python
      uses: actions/setup-python@v4 
      with:
        python-version: '3.9'
    - name: Run build
      run: bash ./build.sh
      shell: bash
